name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CI: true
jobs:
    build_and_lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm format:check

            - name: Build
              run: pnpm build
